### ISSUE TITLE
Boosters should use standalone dependency if they are running tests in standalone mode 

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-organization#33]
I have observed that boosters [1], [2] are using `arquillian-junit-container` dependency even they want to use standalone mode.

Tasks
- [ ] List all boosters which are using `arquillian-junit-container` for standalone mode.
- [ ] Update [boosters parent ](https://github.com/openshiftio/booster-parent/blob/master/pom.xml#L58)to use new version of released cube with https://github.com/arquillian/arquillian-cube/pull/993 merged. 
- [ ]  Update all boosters to use `arquillian-cube-openshift-starter` as single dependency - https://github.com/arquillian/arquillian-organization/issues/35

[1] - https://github.com/snowdrop/spring-boot-http-booster/blob/master/pom.xml#L56
[2] - https://github.com/openshiftio-vertx-boosters/vertx-http-booster/blob/master/pom.xml#L84

**Comment by bartoszmajsak** [comment]
@dipak-pawar are these all boosters with such dependencies? I think we are missing **Wildfly Swarm** if not more.

Another thing - as this inherits Cube version from parent pom - shouldn't we first update this one and ask for the release?

Can we get the list of all boosters first @hemanik? Probably something we could script/figure out from https://github.com/fabric8-launcher/launcher-booster-catalog/tree/master

I believe the update procedure to use `-starter` should be automated.

**Comment by bartoszmajsak** [comment]
This might be handy too https://github.com/fabric8-launcher/launcher-documentation/wiki

**Comment by dipak-pawar** [comment]
> are these all boosters with such dependencies? I think we are missing Wildfly Swarm if not more.

I found above two when I was playing with them. Couldn't find time to check all others. But we should check all others and update it with single dependency.

> Another thing - as this inherits Cube version from parent pom - shouldn't we first update this one and ask for the release?

You are right. You can see second task ` Update boosters parent to use new version of released cube with arquillian/arquillian-cube#993 merged` which is for that only.

> I believe the update procedure to use -starter should be automated.

:+1:

**Comment by bartoszmajsak** [comment]
Let's prepare automation part of it and do actual PRs/contributions to upstream when we have Cube/Che experience improved.

**Comment by hemanik** [comment]
The following needs to be done for the automation part and to do actual PRs/contributions to upstream:

- [ ] Use GitHub APIs to fork and clone the Booster Repositories.

1. Spring Boot boosters are at https://github.com/snowdrop/
2. Vert.x boosters are at https://github.com/openshiftio-vertx-boosters/
3. Swarm boosters are at https://github.com/wildfly-swarm-openshiftio-boosters/

- [ ] Implementation part of `pom` bump to update dependencies.

1. Replace the two arquillian dependencies for `standalone` with the single `starter` dependency. (Dropped from the scope of the automation script since it is a one-time thing.)
2. Update the Arquillian Cube version used if old.

- [ ] Use GitHub APIs to open a PR with the updated pom.xml

**Comment by hemanik** [comment]
Initial Spike for the Automation Script - https://github.com/hemanik/version-bump-automation.

**Comment by hemanik** [comment]
As discussed offline, updating the `starter-dependencies` can be best done manually since it's a one-time thing. 

With regards to this issue then, the following needs to be addressed:
- [x] Update common booster-parent with latest arquillian-cube version. (PR: https://github.com/openshiftio/booster-parent/pull/27)
- [ ] Update individual booster-parent with the new release version of common booster-parent.
- [ ] Update individual booster repositories with `starter-dependency` as tracked by issue https://github.com/arquillian/arquillian-organization/issues/35.

The PRs for the last two tasks on hold for the release of booster-parent with the updated cube version.
